const ADD_PRODUCT = 'ADD_PRODUCT';

const ADD_ALL_PRODUCTS = 'ADD_ALL_PRODUCTS';

const REFRESH_STATE = 'REFRESH_STATE';

const REFRESH_CASE = 'REFRESH_CASE';

export default {
    ADD_PRODUCT,
    ADD_ALL_PRODUCTS,
    REFRESH_STATE,
    REFRESH_CASE
}